services:
  - type: web
    name: hethongchamdiem
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
